#!/usr/bin/env python3

def add():
    a = int(input("Enter a: "))
    b = int(input("Enter b: "))

    return str(a+b)

def main():
    print("the sum is ",add())

if __name__ == "__main__":
    main()

